website/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail

db = SQLAlchemy()
DB_NAME = "database.db"
mail = Mail()


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'PADE_USA'
    app.config['SQLALCHEMY_DATABASE_URL'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    
    app.config['MAIL_SERVER']='smtp.mailtrap.io'
    app.config['MAIL_PORT'] = 2525
    app.config['MAIL_USERNAME'] = '97e041d5e367c7'
    app.config['MAIL_PASSWORD'] = 'cfaf5b99f8bafb'
    app.config['MAIL_USE_TLS'] = True
    app.config['MAIL_USE_SSL'] = False
    
    # with app.open_resource("modified_text_file.txt") as fp:  
    #  mail.attach("modified_text_file.txt", "text/txt", fp.read())  
    mail.init_app(app)
    
    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    return app

website/auth.py
from flask import Blueprint

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return "<p>Login</p>"

@auth.route('/logout')
def logout():
    
    return "<p>Logout</p>"

@auth.route('/sign-up')
def signup():
    return "<p>signup</p>"
   

website/views.py
# from crypt import methods
# from distutils.log import error
# from email.policy import EmailPolicy
# from operator import contains
import os
from re import M
from flask import Blueprint, flash, redirect, render_template, request, send_file
from flask_mail import Mail, Message
from . import mail

views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template('home.html')

@views.route('/analysis', methods = ['GET', 'POST'])
def analysis():
    if request.method == 'POST':
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        email = request.form.get('email')
        e_coil = request.form.get('e_coil')
      #  modify =request.form.get('modify')
        if len(firstName)<2 :
            flash('First name must be greater one character...',category='error')
        elif len (lastName)<2 :
            flash('Last name must be greater one character...', category='error')
        elif len(email)<2 :
             flash('Invalid email address...', category='error')
        #elif 'txt' not in e_coil:
             #flash('Invalid file ...', category='error')
       # elif len(modify)<2:
            #flash('Invalid modiflier ...', category='error')
        else:
           #create the dictionary
            dictionary = { 'D' : '(Kunpo)' , 'A' : 'mnm' }
            #open the text file in read only mode
            if request.files:
                file = request.files['e_coil']
             
                text_file = file.readlines()
               
                  #To open a modified text file
                modified_text_file = open("modified_text_file.txt", "w")
                
                for line in text_file:
                    
                 mline = line.decode()
                 if mline[0] != ">":   #To skip every line that starts with '>' in the text file
                        for key in dictionary:
                            mline = mline.replace(key, dictionary[key])  #To perform the replacement using the values of the created dictionary
                            modified_text_file.write(mline)
                            # print(mline)
                        
                        else:
                            modified_text_file.write(mline)
                            # print(mline)
                # modifiedFile = modified_text_file.readlines()  
                # moddecode = modifiedFile.decode()
                         
                print(modified_text_file.readable())  
                # with app.open_resource("invoice.pdf") as fp:  
                #     msg.attach("invoice.pdf", "application/pdf", fp.read())  
                
                # msg = Message('Hello', sender = 'daramolaadekunle15@gmail.com', recipients = [email])
                # msg.body = "This is the email body"
                # msg.attach("modified_text_file.txt", "text/txt")
                # mail.send(msg)     
                modified_text_file.close()
                p = "modified_text_file.txt"
                print(p)
                # filename = os.path.join( 'E-COIL', 'modified_text_file.txt')
                # send_file(p, as_attachment=True)
                        
                # return redirect('/download') 
                return render_template('download.html')       
                # flash('File formated successful And Formated file sent to your email', category='success')
               
             
                
    # data = request.form
    
    return  render_template('analysis.html') 

@views.route('/contact')
def contact():
    return render_template('download.html')

@views.route('/download')
def download_file():
    p = "modified_text_file.txt"
    return render_template('download.html')
    # return send_file(p, as_attachment=True)

website/templates/analysis.html
{% extends "index.html" %}
{% block title %} Analysis {% endblock %}

{% block content %}

<form method = "POST" enctype="multipart/form-data">
<h3 align ="center"> Here the E-coli sequences in FASTA format </h3>
<div class ="form-group">
    
    <label for ="firstName"> First Name </label>
    <input type="text"
     class = "form-control" 
     id = "firstName" 
     name = "firstName" 
     placeholder = "Enter FirstName">
    </input>

</div>
<div class ="form-group">
  <label for ="lastName"> Last Name </label>
  <input type="text"
   class = "form-control" 
   id = "lastName" 
   name = "lastName" 
   placeholder = "Enter Last Name">
  </input>

</div>

<div class ="form-group">
  <label for ="email"> Email </label>
<input type="email"
 class = "form-control" 
 id = "email" 
 name = "email" 
 placeholder = "Email">
</input>
</div>


<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">E-coli sequences </span>
  </div>
  <div class="custom-file">
    <input type="file" class="custom-file-input" id="e_coil" name="e_coil">
    <label class="custom-file-label" for="e_coil">Choose file</label>
  </div>
</div>

 
<br>
<button type ="submit"  onclick="window.location.href='{{ url_for( 'views.download_file' ) }}';"  class = "btn btn-primary btn-lg btn-block" value="editor"> Submit </button>

</form>

 {% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <title>{% block title %} Home {% endblock %}</title>
</head>

<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">E-Coil</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" id="home" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" id="home" href="/analysis">Analysis <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id ="about" href="/contact">Contact</a>
                </li>
              
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
    {% for category, message in  messages %}
    {% if category == 'error' %}

    <div class ="alert alert-danger alter-dismissable fade show" role ="alert"> 
        {{ message }}
        <button type="button" class ="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    {% else %}
    <div class ="alert alert-success alter-dismissable fade show" role ="alert"> 
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    
    {% endif %}
    
    {% endfor %}
    {% endif  %}
    {% endwith %}

    <div class = "container">
        {% block content %} {% endblock %}
    </div>
</body>

</html>

website/templates/contact.html
{% extends "index.html" %}
{% block title %} Contact {% endblock %}
{% block content %} 
<div class="address">
    <p>email:S0olap01@gmail.com</p>
    <p>phone:+23432354454</p>


<div class="form-group" >
    <label for ="e_coil"> E-coli sequences  </label>
    <div class="form-group">
      <input type="file" class="custom-file-input" placeholder="E-coli sequences"
      name ="e_coil" id="e_coil">
      
    </div>
  </div>
</div>
{% endblock %}

website/templates/download.html
{% extends "index.html" %}
{% block title %} Download {% endblock %}


{% block content %} 
<div class="text-wrap">
    <h1 class="text">Your file is ready for download.</h1>
    <p>On this page you will have access to E-coli RNA FASTA sequence</p>
    <a href="{{url_for('views.download_file')}}">Download</a>

</div>
{% endblock %}

website/templates/home.html
{% extends "index.html" %}
{% block title %} Home {% endblock %}


{% block content %} 
<div class="text-wrap">
    <h1 class="text">Welcome to Segun's page.</h1>
    <p>On this page you will have access to E-coli RNA FASTA sequence</p>
</div>
{% endblock %}

website/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <title>{% block title %} Home {% endblock %}</title>
</head>

<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">E-Coil</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" id="home" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" id="home" href="/analysis">Analysis <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id ="about" href="/contact">Contact</a>
                </li>
              
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
    {% for category, message in  messages %}
    {% if category == 'error' %}

    <div class ="alert alert-danger alter-dismissable fade show" role ="alert"> 
        {{ message }}
        <button type="button" class ="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    {% else %}
    <div class ="alert alert-success alter-dismissable fade show" role ="alert"> 
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    
    {% endif %}
    
    {% endfor %}
    {% endif  %}
    {% endwith %}

    <div class = "container">
        {% block content %} {% endblock %}
    </div>
</body>

</html>